### ISSUE TITLE
SR Linux Documentation not matching CLI config options

### ISSUE THREAD

**Issue by pedroaston** [srl-labs/learn-srlinux#155]
## Problem Statement

For IS-IS, the CLI configuration exposed in the documentation does not match the CLI config in the SR Linux device itself. Is the documentation not updated, or is there another issue? In here, I focused only on IS-IS authentication related configs.

## Problem Details

SR Linux version >> 23-3
Container image download link >> ghcr.io/nokia/srlinux:23.3.3-11
Emulated in containerLab v0.55.1
Documentation link >> https://documentation.nokia.com/srlinux/23-3/books/routing-protocols/is-is.html

#### CLI IS-IS defaults in the device
![image](https://github.com/srl-labs/learn-srlinux/assets/36762762/40582c8e-ee59-47eb-a2d8-b8c7b6e97815)

#### CLI IS-IS defaults presented in the documentation
![image](https://github.com/srl-labs/learn-srlinux/assets/36762762/b46faf60-286a-4be3-b654-df36e557ab80)

Thanks

**Comment by hellt** [comment]
Hi @pedroaston 
yes, looks like a documentation issue. You can report this to the docs team using the link in the docs page
