### ISSUE TITLE
mpls-ldp lab fails to accept the config

### ISSUE THREAD

**Issue by cgo-chong** [srl-labs/learn-srlinux#99]
Hi, I met the error which showed in the below picture. 
![图片](https://github.com/srl-labs/learn-srlinux/assets/145850775/01c0a993-814d-4f1e-ab46-8230c0774a08)
And the yml is
![图片](https://github.com/srl-labs/learn-srlinux/assets/145850775/4e319da8-1762-4cfd-ace7-09e1915cf8c7)

**Comment by hellt** [comment]
thanks, I will have a look.
The error message is related to the changed config syntax, but I will have to check where we missed updating it here.

**Comment by hellt** [comment]
Just got to it.
Fixed in https://github.com/srl-labs/learn-srlinux/commit/d4a20c3851cdca398486c54292791a6bf6bb02ae should be way better now.
Thank you for reporting this.
